version: '2'
services:
  nginx-proxy:
    image: cheminfo/eln-nginx-proxy
    ports:
      # Map application to local port
      - '4444:80'
    links:
      - couchdb
      - rest-on-couch
      - flavor-builder
    #Uncomment to add web assets
    #volumes:
    #  - ./www-assets:/data/www/

  couchdb:
    image: cheminfo/eln-couchdb
    environment:
      # Customize CouchDB admin credentials
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password
    volumes:
      # Map local CouchDB data directory
      - /usr/local/couchdb:/usr/local/var/lib/couchdb/

  rest-on-couch:
    image: cheminfo/rest-on-couch:v3.3.0
    command: pm2-docker start /pm2-rest-on-couch.yaml
    expose:
      - 3000
    environment:
      DEBUG: 'couch:error,couch:warn,couch:debug'
    volumes:
      - ./pm2-rest-on-couch.yaml:/pm2-rest-on-couch.yaml
    # Map local roc home directory
      - /usr/local/rest-on-couch:/rest-on-couch
    links:
      - couchdb

  rest-on-couch-import:
    image: cheminfo/rest-on-couch:v3.3.0
    command: pm2-docker start /pm2-roc-import.yaml
    environment:
      DEBUG: 'couch:error,couch:warn,couch:debug'
      REST_ON_COUCH_LOG_LEVEL: 'FATAL'
    volumes:
    # Map local roc home directory
      - /usr/local/rest-on-couch:/rest-on-couch
      - ./pm2-roc-import.yaml:/pm2-roc-import.yaml
    links:
      - couchdb

  flavor-builder:
    image: cheminfo/eln-flavor-builder
    environment:
      DEBUG: 'flavor-builder*'
      # Customize CouchDB admin credentials
      # They must be the same as in the "couchdb" container
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password
    # Uncomment to use a custom flavor-builder config
    # This is usually unnecessary
    #volumes:
    #  - /usr/local/flavor-config.json:/flavor-config.json
    links:
      - couchdb

  printer-proxy:
    image: cheminfo/eln-printer-proxy
    command: pm2-docker start /pm2-proxy.yml
    volumes:
      - ./printer-proxy-config.yml:/config.yml
    links:
      - rest-on-couch
    expose:
      - 7770
