version: '2'
services:
  nginx-proxy:
    image: cheminfo/eln-nginx-proxy
    ports:
      # Map application to local port
      - '4444:80'
    depends_on:
      - couchdb
    links:
      - couchdb
      - rest-on-couch
      - flavor-builder

  couchdb:
    image: cheminfo/eln-couchdb
    environment:
      COUCHDB_USER: admin
      # Customize password
      COUCHDB_PASSWORD: password
    volumes:
      # Map local CouchDB data directory
      - /usr/local/couch:/usr/local/var/lib/couchdb/

  rest-on-couch:
    image: cheminfo/rest-on-couch
    command: pm2-docker start /git/rest-on-couch/node_modules/rest-on-couch/bin/rest-on-couch-server.js
    expose:
      - 3000
    environment:
      DEBUG: 'couch:error,couch:warn,couch:debug'
    volumes:
    # Map local roc home directory
      - /usr/local/rest-on-couch:/rest-on-couch
    depends_on:
      - couchdb

  rest-on-couch-import:
    image: cheminfo/rest-on-couch
    command: pm2-docker start /roc-import.json
    environment:
      DEBUG: 'couch:error,couch:warn,couch:debug'
      REST_ON_COUCH_LOG_LEVEL: 'fatal'
    volumes:
    # Map local roc home directory
      - /usr/local/rest-on-couch:/rest-on-couch
      - ./roc-import.json:/roc-import.json
    depends_on:
      - couchdb

  flavor-builder:
    image: cheminfo/eln-flavor-builder
    # Uncomment to use a custom flavor-builder config
    # volumes:
    #   - /usr/local/flavor-config.json:/flavor-config.json
    depends_on:
      - couchdb
