rest-on-couch:
  url: http://rest-on-couch:3000 # DO NOT CHANGE
  database: printers # in most cases no need to change this
  username: admin@cheminfo.org # DO NOT CHANGE
  password: password # change here