rest-on-couch:
  url: https://eln.epfl.ch/roc/ # DO NOT CHANGE
  database: printers # in most cases no need to change this
  username: admin@cheminfo.org # DO NOT CHANGE
  password: password # change here
